const env = require("../config/env");

let genAIClient = null;
if (env.geminiApiKey) {
  try {
    const { GoogleGenAI } = require("@google/genai");
    genAIClient = new GoogleGenAI({ apiKey: env.geminiApiKey });
  } catch (e) {
    console.warn("[AI Service] @google/genai initialization note:", e.message);
  }
}

const aiService = {
  /**
   * Summarize medical record or lab report with compliance disclaimer
   */
  async summarizeMedicalRecord(title, vitals = {}, notes = "") {
    const medicalDisclaimer = "\n\n⚠️ Disclaimer: This informational summary is generated by LifeSync AI for record organization only and does not constitute medical diagnosis, clinical evaluation, or treatment advice. Consult your certified healthcare physician for any medical concerns.";

    const vitalsStr = Object.entries(vitals || {})
      .filter(([_, v]) => v !== undefined && v !== null && v !== "")
      .map(([k, v]) => `${k}: ${v}`)
      .join(", ");

    if (genAIClient && env.geminiApiKey) {
      try {
        const response = await genAIClient.models.generateContent({
          model: "gemini-2.5-flash",
          contents: `You are a medical records assistant. Summarize the following health entry concisely in plain language for a patient record:
Title: ${title}
Vitals: ${vitalsStr || "None noted"}
Notes: ${notes || "None noted"}

Explain the metrics in plain, encouraging language. Keep it under 3 sentences. Do not prescribe anything.`
        });

        const reply = response.text || "";
        return `${reply.trim()}${medicalDisclaimer}`;
      } catch (err) {
        console.warn("[Gemini API Error, falling back to local medical logic]:", err.message);
      }
    }

    // High quality contextual local medical summarizer
    let summary = `Recorded "${title}". `;
    if (vitals.systolic && vitals.diastolic) {
      const bpStatus = vitals.systolic < 120 && vitals.diastolic < 80 ? "optimal" : "noted for follow-up";
      summary += `Blood pressure is ${vitals.systolic}/${vitals.diastolic} mmHg (${bpStatus}). `;
    }
    if (vitals.heartRate) {
      summary += `Resting pulse recorded at ${vitals.heartRate} bpm. `;
    }
    if (vitals.bloodGlucose) {
      summary += `Fasting glucose is ${vitals.bloodGlucose} mg/dL. `;
    }
    if (notes) {
      summary += `Observation note: "${notes}".`;
    }

    return `${summary.trim()}${medicalDisclaimer}`;
  },

  /**
   * Contextual LifeSync Copilot that queries across all collections
   */
  async askCopilot(userPrompt, contextData) {
    const { userName, expenses = [], documents = [], tasks = [], healthRecords = [] } = contextData;

    // Total expenses & category map
    let totalSpent = 0;
    let totalIncome = 0;
    const expenseCategories = {};
    expenses.forEach((e) => {
      const amt = Number(e.amount) || 0;
      if (e.type === "income") totalIncome += amt;
      else {
        totalSpent += amt;
        expenseCategories[e.category] = (expenseCategories[e.category] || 0) + amt;
      }
    });

    const pendingTasks = tasks.filter((t) => t.status !== "completed");
    const urgentTasks = pendingTasks.filter((t) => t.priority === "high");

    // If Gemini API is configured
    if (genAIClient && env.geminiApiKey) {
      try {
        const systemContext = `You are LifeSync Copilot, an intelligent, empathetic, and ultra-precise personal assistant for ${userName}.
You have direct, authenticated access to the user's personal vault data:
- Financial Ledger: Total Income: $${totalIncome.toFixed(2)}, Total Spent: $${totalSpent.toFixed(2)}, Net: $${(totalIncome - totalSpent).toFixed(2)}. Top expense categories: ${JSON.stringify(expenseCategories)}. Recent entries: ${expenses.slice(0, 5).map((e) => `${e.category}: $${e.amount}`).join(", ")}.
- Document Vault (${documents.length} files): ${documents.slice(0, 5).map((d) => `${d.title} (${d.category}, Expiry: ${d.extractedMetadata?.expiryDate || 'N/A'})`).join(", ")}.
- Active Tasks (${pendingTasks.length} pending, ${urgentTasks.length} high priority): ${pendingTasks.slice(0, 5).map((t) => `[${t.priority.toUpperCase()}] ${t.title} (Due: ${t.dueDate ? new Date(t.dueDate).toLocaleDateString() : 'None'})`).join(", ")}.
- Health Logs (${healthRecords.length} records): Latest record: ${healthRecords[0]?.title || "None"}.

Answer the user's question directly, accurately citing their actual figures. Format cleanly with bullet points or bold text if helpful.`;

        const response = await genAIClient.models.generateContent({
          model: "gemini-2.5-flash",
          contents: `${systemContext}\n\nUser Question: ${userPrompt}`
        });

        return response.text;
      } catch (err) {
        console.warn("[Gemini API Error, falling back to local reasoning engine]:", err.message);
      }
    }

    // Professional Local Context-Retrieval Engine
    const q = userPrompt.toLowerCase();

    // 1. Financial queries
    if (q.includes("spend") || q.includes("expense") || q.includes("money") || q.includes("cost") || q.includes("budget") || q.includes("income") || q.includes("saving")) {
      const topCat = Object.entries(expenseCategories).sort((a, b) => b[1] - a[1])[0];
      let reply = `Here is your current financial summary, **${userName}**:\n\n`;
      reply += `• **Total Expenses**: $${totalSpent.toFixed(2)} across ${expenses.filter((e) => e.type !== "income").length} transactions\n`;
      reply += `• **Total Income**: $${totalIncome.toFixed(2)}\n`;
      reply += `• **Net Savings**: $${(totalIncome - totalSpent).toFixed(2)}\n`;
      if (topCat) {
        reply += `• **Top Category**: **${topCat[0]}** ($${topCat[1].toFixed(2)})\n`;
      }
      if (q.includes("grocery") || q.includes("food")) {
        const foodTotal = expenseCategories["Food"] || 0;
        reply += `\nSpecifically for **Food/Groceries**, you have spent **$${foodTotal.toFixed(2)}**.`;
      }
      return reply;
    }

    // 2. Task & Deadline queries
    if (q.includes("task") || q.includes("todo") || q.includes("deadline") || q.includes("urgent") || q.includes("pending")) {
      if (pendingTasks.length === 0) {
        return `You have zero pending tasks! Everything on your to-do list is complete. 🎉`;
      }
      let reply = `You currently have **${pendingTasks.length} pending tasks** (${urgentTasks.length} high priority):\n\n`;
      pendingTasks.forEach((t) => {
        const due = t.dueDate ? ` — Due: ${new Date(t.dueDate).toLocaleDateString()}` : "";
        const tag = t.priority === "high" ? "🔴 [High]" : t.priority === "medium" ? "🟡 [Medium]" : "🟢 [Low]";
        reply += `• ${tag} **${t.title}**${due}\n`;
      });
      return reply;
    }

    // 3. Document Vault queries
    if (q.includes("document") || q.includes("file") || q.includes("vault") || q.includes("tax") || q.includes("insurance") || q.includes("pdf")) {
      if (documents.length === 0) {
        return `Your document vault is currently empty. You can drag and drop PDF or image documents in the **Documents** tab.`;
      }
      let reply = `You have **${documents.length} secure documents** stored in your vault:\n\n`;
      documents.forEach((d) => {
        const issuer = d.extractedMetadata?.issuer ? ` (${d.extractedMetadata.issuer})` : "";
        reply += `• **${d.title}** — *${d.category}*${issuer} [${(d.fileSizeBytes / 1024 / 1024).toFixed(2)} MB]\n`;
      });
      return reply;
    }

    // 4. Health & Vitals queries
    if (q.includes("health") || q.includes("vital") || q.includes("medical") || q.includes("blood") || q.includes("pressure") || q.includes("doctor")) {
      if (healthRecords.length === 0) {
        return `You haven't logged any health records or vitals yet. Visit the **Health** tab to log your blood pressure, heart rate, or lab reports.`;
      }
      const latest = healthRecords[0];
      let reply = `Here is your latest health overview based on **${healthRecords.length} recorded entries**:\n\n`;
      reply += `• **Latest Record**: ${latest.title} (${new Date(latest.recordDate).toLocaleDateString()})\n`;
      if (latest.vitals?.systolic) {
        reply += `• **Vitals**: BP ${latest.vitals.systolic}/${latest.vitals.diastolic} mmHg, Heart Rate ${latest.vitals.heartRate} bpm\n`;
      }
      if (latest.aiSummary) {
        reply += `• **Clinical Summary**: ${latest.aiSummary}\n`;
      }
      return reply;
    }

    // 5. Daily Briefing / Overview catch-all
    return `Hello **${userName}**! Here is your daily LifeSync briefing:\n\n` +
      `• 💰 **Finances**: Spent $${totalSpent.toFixed(2)} | Net savings $${(totalIncome - totalSpent).toFixed(2)}\n` +
      `• 📋 **Tasks**: ${pendingTasks.length} pending (${urgentTasks.length} urgent)\n` +
      `• 📂 **Vault**: ${documents.length} encrypted documents stored\n` +
      `• ❤️ **Health**: ${healthRecords.length} health and vitals records logged\n\n` +
      `Ask me anything specific, like *"What are my highest expenses?"*, *"Do I have any urgent tasks?"*, or *"Show my recent health records"*.`;
  }
};

module.exports = aiService;
